### ISSUE TITLE
looks broken with subsonic 5.3 (build 4568)

### ISSUE THREAD

**Issue by krodelabestiole** [ronilaukkarinen/rolleshark#5]
hello i tried to install this theme on subsonic 5.3 (build 4568) but i ran on a few issues :
- first the install script wont work with any other version than 4427
  maybe it would be better to present a list of command line to adapt depending on the version
- then the design looks broken, i'm joining a screenshot, there's a few more little issues i haven't mentioned
  ![subsonic](https://cloud.githubusercontent.com/assets/409655/11078257/ac054b2e-87fc-11e5-9446-04b88a932d99.png)

**Comment by krodelabestiole** [comment]
and when i try to switch back to a former theme i've got an error :

> Error
> Subsonic encountered an internal error. You can report this error in the Subsonic Forum. Please include the information below.
> 
> Exception  javax.servlet.ServletException
> Message    javax.servlet.jsp.JspTagException: Theme 'darksub': No message found under code 'styleSheet' for locale 'en'.

so i cannot use soundcloud anymore (no access to settings) - i will try to revert the files

**Comment by jamoir** [comment]
I also have the same problem on 5.3. Copied over the files using the install_vanilla.sh and it broke subsonic, straight to the error. Only way to fix was to reinstall subsonic.

**Comment by rollecode** [comment]
Sorry for getting back to this so late, been busy... it's noteworthy that this theme is not compatible on newer vanilla subsonic or not tested on those versions. I have been doing some debugging with newer subsonic versions but since I use musiccabinet version (because of the awesome Last.fm integration) there won't be a 100% vanilla subsonic version any time soon. If you want, you can help to fix it and send a pull request.

I have to close this and add a note to README...

**Comment by rollecode** [comment]
@krodelabestiole @jamoir FYI, Madsonic 6.1 support is now available. Still not tested on Vanilla Subsonic, can't promise support for that I'm afraid. I hope madsonic theme helps though.
